### PR TITLE
Credit card number detection module

### PR DESCRIPTION
**Pull request by scooterhanson**
Added a variation of the contents module with a set of patterns for credit card numbers, and it runs each hit through a [luhn algorithm check](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi19pSl4NDXAhVrwFQKHQ4DCtoQFggmMAA&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FLuhn_algorithm&usg=AOvVaw3g4sKY3lNNjhPD7mq9JHPJ) to validate that it is a card number.  See [#30](https://github.com/Stono/hawkeye/issues/30)

### CODE REVIEW

**Comment by Stono** [comment]
Please see my comments on https://github.com/Stono/hawkeye/pull/17

**Comment by scooterhanson** [comment]
What's up with that?

**Comment by Stono** [comment]
Ah it's actually me not setting travis up right for multi-branch.... bear with me...

**Comment by Stono** [comment]
@scooterhanson can I close this as you've pulled it into https://github.com/Stono/hawkeye/pull/17 and we just deal with all your work there?

**Comment by scooterhanson** [comment]
Go for it

**Pull request closed without merging**
