### PR TITLE
Fixing issues 15 and 14/16, Adds ccnumbers and level threshold

### PR DESCRIPTION
**Pull request by scooterhanson**
The entropy search was failing with regex reserved characters - changing this to a `split()` fixed the issue.

On the RangeError issue for large codebases, adding a `setTimeout()` around the file recursion solved this with minimal overhead.

### CODE REVIEW

**Comment by Stono** [comment]
Hey mate,
Thanks so much for the pull request, and apologies for taking a week to look at it - i've been away.
I have to be honest I'm confused why a setTimeout with a 0 does anything at all?  Could you explain?

Karl

**Comment by Stono** [comment]
Hey, please see https://github.com/Stono/hawkeye/commit/39a8468c92ef2915a8800971c21e0725c0dcfd84 which I believe addresses the callstack issue without the setTimeouts.

**Comment by scooterhanson** [comment]
Awesome!  I'll get that swapped out shortly.

**Comment by scooterhanson** [comment]
Took me long enough to get around to this -- sorry -- but it's done.

**Comment by Stono** [comment]
@scooterhanson I feel like I need to take a day off just to look through your pull requests, haha!  Thank you so much for your efforts.  I'll gradually pick them up today.

**Comment by Stono** [comment]
@scooterhanson unfortunately I can't merge your changes as it would break the build, there are a lot of jshint errors:

```
   lib/modules/ccnumber/index.js
     26 |        const isolatedItem = item.replace(/(\d+)([ -])(\d+)/g,"$1$3")
                                                                             ^ Strings must use singlequote.
     27 |                                 .replace(/(\d+)([ -])(\d+)/g,"$1$3")
                                                                             ^ Strings must use singlequote.
     28 |                                 .replace(/(\d+)([ -])(\d+)/g,"$1$3")
                                                                             ^ Strings must use singlequote.
     29 |                                 .replace(/(\D)(\d{15,})/g, "$1 $2")
                                                                            ^ Strings must use singlequote.
     30 |                                 .replace(/(\d{15,})(\D)/g, "$1 $2");
                                                                            ^ Strings must use singlequote.
     20 |    const patterns = require(options.patterns);
                   ^ 'patterns' is defined but never used.
   lib/modules/ccnumber/luhn.js
      5 |        var trimmed = String(cardNumber).replace(/[\s]/g, "")
                                                                     ^ Strings must use singlequote.
      6 |            , length = trimmed.length
                     ^ Comma warnings can be turned off with 'laxcomma'.
      5 |        var trimmed = String(cardNumber).replace(/[\s]/g, "")
                                                                     ^ Misleading line break before ','; readers may interpret this as an expression boundary.
      6 |            , length = trimmed.length
                                        ^ Misleading line break before ','; readers may interpret this as an expression boundary.
      7 |            , odd = false
                             ^ Misleading line break before ','; readers may interpret this as an expression boundary.
      8 |            , total = 0
                               ^ Misleading line break before ','; readers may interpret this as an expression boundary.
      9 |            , calc
                       ^ Misleading line break before ','; readers may interpret this as an expression boundary.
      4 |    function validate(cardNumber){
                              ^ This function's cyclomatic complexity is too high. (10)
```

As well as one failing test:
```
 100 passing (451ms)
  1 failing

  1) Scan
       should run a scan:

      Uncaught AssertionError: expected 6 to equal 5
      + expected - actual

      -6
      +5
```

**Comment by Stono** [comment]
Lots of the issues appear to be in your ccnumbers work, which i presume shouldn't be included in the PR and instead https://github.com/Stono/hawkeye/pull/32?

**Comment by Stono** [comment]
Wow I just realised a whole load of them were actually as a result of the python work that was recently merged (obviously I forgot the due diligence there!).

I have fixed all jshint errors in `master` so if you pull in from `stono:master` then you'll know any remaining jshint errors are a result of your stuff :-)

**Comment by scooterhanson** [comment]
Awesome.  Thanks for that.  Not sure I'll have time to do much in the next couple of days, but I'll do a fetch and see what it looks like for me.

**Comment by Stono** [comment]
@scooterhanson I think i've finally fixed my tavis woes!  If you want to pull from `master` and push up here, hopefully it'll go green!

**Comment by scooterhanson** [comment]
@Stono I can't figure out why the build is failing to run a scan.  Any clues on your end?

**Comment by Stono** [comment]
@scooterhanson The build is broken because of a single failing test:

```
  100 passing (597ms)
  1 failing
  1) Scan
       should run a scan:
      Uncaught AssertionError: expected 6 to equal 5
      + expected - actual
      -6
      +5
```

Looking at the test, L37 where it is failing says `should(results.length).eql(5);`, looks like the scan is returning 6 results rather than 5.  The results here is an array of modules that ran.  If you console out those results you'll see one which isn't there in the `master` branch, and that is:

```
[ { module:
     { key: 'ccnumber',
       name: 'Credit Card Numbers',
       description: 'Scans files for potential credit card numbers',
       enabled: true,
       handles: [Function],
       run: [Function] },
    results: { high: [], medium: [], low: [], critical: [] } },
```

Subsequently the test needs to be updated to 6.  Whilst you're there you could probably reword the test to something like `it should run a scan and return results for each of the enabled modules`.

You also have some jshint issues:

```
❯ grunt
Running "jshint:stdout" (jshint) task

   lib/modules/ccnumber/luhn.js
     14 |                sum += (bit ^= 1) ? arr[val] : val;
                                     ^ Unexpected use of '^='.
   lib/scan.js
     14 |const ModuleResults = function(module,rc) {
                                               ^ 'rc' is defined but never used.
     59 |    return results.map(result => {
                                          ^ This function's cyclomatic complexity is too high. (5)
```

`rc` is being passed to `ModuleResults` but then not used.    

For the luhn one, you'll need to disable bitwise in jshint at the top of the file with `/*jshint bitwise: false*/`.

As for the cyclomatic complexity one you'll need to break that into smaller function.  Although for now i'll be ok with a `/* jshint maxcomplexity: 6 */` putting above it just to get these large amount of changes through.

Hope this helps

**Comment by scooterhanson** [comment]
Thank you for pointing me in the right direction!  Much appreciated.

**Comment by Stono** [comment]
Great stuff @scooterhanson - thanks for your hard work!

**Comment by Stono** [comment]
Version `0.20.0` will be pushed when https://travis-ci.org/Stono/hawkeye/builds/316308219 completes!

**Comment by Stono** [comment]
Oh just realised @scooterhanson you've missed a section in the README for the CCNumbers bit: https://github.com/Stono/hawkeye#generic-modules 

Could you whack in another quick PR that promotes this new feature? Ta!

**Comment by Stono** [comment]
In fact, I'll sort it :-)

**Pull request merged**
