### PR TITLE
Update fileLimit

### PR DESCRIPTION
**Pull request by dspringer**

### CODE REVIEW

**Comment by Stono** [comment]
Hey @dspringer - 5000 files seems quite a lot?
Are you sure we don't just need to tweak the 'excludes' to ensure we're not scanning things that don't need scanning?

**Comment by dspringer** [comment]
Hi Karl,

You are absolutely right. The project in question is actually just 1022
files (for now) and likely won't grow passed 1500. I only submitted for
5000 because I didn't understand why the limit is set to 1000, as the
number seemed self-imposed. The team that needs this project scanned likely
can add some things to their exclude, but they will likely be constantly
teetering on the edge and will spend some amount of time trying to tailor
the project to stay under 1000.

On Nov 2, 2017 6:42 AM, "Karl Stoney" <notifications@github.com> wrote:

Hey @dspringer <https://github.com/dspringer> - 5000 files seems quite a
lot?
Are you sure we don't just need to tweak the 'excludes' to ensure we're not
scanning things that don't need scanning?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Stono/hawkeye/pull/20#issuecomment-341382412>, or mute
the thread

**Comment by Stono** [comment]
Hey! 
So perhaps a better solution here is to allow people to control the file limit in the .hawkeyerc file for the CLI version.

I need to keep a sensible limit (albeit i'm unsure what quantifies as sensible) to protect the SaaS version from dossing.

hmm i'll think some more

**Comment by dspringer** [comment]
Ahhhhh I understand a bit more now, there definitely should be more
restrictions for the SaaS implementation. I am actually using the docker
version of the tool (recall the tools issues with Ubuntu and other Linux
systems). This mimics the CLI correct? Would the target directory need to
have it's own .hawkeyerc before the scan is run?

On Nov 2, 2017 10:10 AM, "Karl Stoney" <notifications@github.com> wrote:

Hey!
So perhaps a better solution here is to allow people to control the file
limit in the .hawkeyerc file for the CLI version.

I need to keep a sensible limit (albeit i'm unsure what quantifies as
sensible) to protect the SaaS version from dossing.

hmm i'll think some more

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Stono/hawkeye/pull/20#issuecomment-341432841>, or mute
the thread

**Comment by Stono** [comment]
Hey, yes that mimics the CLI, it just runs it in a container.
The hawkeyerc is optional, but it used to override some of the variables which are available via the command line parameters

https://github.com/Stono/hawkeye#hawkeyerc

I think "fileLimit" would be a good addition, which is simply ignored on the SaaS solution.

I'm happy to implement that, but it probably won't be until the weekend!

**Comment by ardeshireshghi** [comment]
@dspringer @Stono So I finally spent time with a colleague of mine and added this feature: https://github.com/Stono/hawkeye/pull/58

**Comment by felixhammerl** [comment]
Following https://github.com/Stono/hawkeye/issues/27, I removed the file limit in https://github.com/Stono/hawkeye/commit/313199ae7442337b773b9f974c038b9b2e7e307b by defaulting it to MAX_SAFE_INTEGER

**Pull request closed without merging**
