### PR TITLE
Proposal to fix #52

### LINKED ISSUE #52: can't identity language specific tests in subdirectories
Hawkeye wasn't scanning my ruby app located in a subdirectory of my repo:

[info] Not Handling Brakeman Scan
[info] Not Handling Bundler Scan

... until I scoped the scan specifically to the subdirectory where the Gemfile is

[info] Running module Brakeman Scan
[info]  -> brakeman . -f json -o /target/inventory_web/output.json
[info] Running module Bundler Scan
[info] Updating bundler-audit database...
[info]  -> bundle-audit update
[info]  -> bundle-audit 

So the language specific tests don't appear to work in subdirectories.

Please advise, Thanks,
Nate

### PR DESCRIPTION
**Pull request by nicolastrres**
After some investigation about the issue #52, I found that usually the modules are run based on some condition, for example, ruby modules only run if they find a Gemfile, the problem is that Hawkeye is only looking for the files on the root directory.

This is because the `exists` function of the fileManager looks for the files on the `files` object which contains the complete path of the files, so for example if a Gemfile is on a subdirectory, the file path on the files object will be `subdirectory/Gemfile` which won't be equal to `Gemfile` and because of that the ruby module won't run.  

This PR contains the logic to get all the files names from the files objects, and iterate over them to see if there is a file called Gemfile. 

@Stono , I would like to hear from you if this makes sense or if there is a better way to solve this issue. 
If we decide to go this way, I can implement a similar logic for the other modules.

### CODE REVIEW

**Comment by nicolastrres** [comment]
hi @Stono, any feedback on this?

**Comment by Stono** [comment]
Hey mate, sorry - I don't really maintain hawkeye any more as I'm crazy busy.  I promise to take a look at this tomorrow though!

**Comment by Stono** [comment]
hey @nicolastrres - what happens if a folder contains multiple Gemfiles?

**Comment by nicolastrres** [comment]
hey @Stono sorry, I didn't have time to verify the behavior before. I've just verified,  and when there are multiple Gemfiles in different folders brakeman runs, however, it does not run in every folder it runs only on one of the folders containing the Gemfile.
So for example, if we have  the following structure
```
src/
    subproj1/
        Gemfile
    subproj2/
         Gemfile
```
Brakeman will only run against subproj1.

I could make some logic to iterate through all folders containing the Gemfile and run brakeman, but. it does not seem a good strategy, and not sure if worth the effort to make it (it seems like an exception).

After thinking about it, my feeling is that handle projects with Gemfile in subfolders is making the code more complex and not sure if is the way we would like to go. Probably, it would be better to keep the code simple and solve the 90% of use cases and not focus on the exceptions like this one.

**Comment by felixhammerl** [comment]
Thanks for the PR. Was just reviewing it, and as you said I think it makes more sense to run Hawkeye in the subfolders, rather than the strategy outlined here. Hawkeye was built with the intention of running top-level in a project, where the configuration and package management resides, and as the subprojects are in itself independent projects, I'd vote for keeping it simple :)

If that's ok, I'll close the PR for now...

**Pull request closed without merging**
